nome = str(input('Digite seu nome completo: ')).lower().strip()
print('A letra A aparece {} no seu nome'.format(nome.count('a')))
print('A primeira letra A apareceu na posição {}'.format(nome.find('a')+1))
print('A última letra A apareceu na posição {}'.format(nome.rfind('a')+1))
print('Seu nome possui {} letras'.format(len(nome)))