numero = int(input('Digite um número: '))
print('-' * 15)
print('{} x {} = {}'.format(numero, 1, numero*1))
print('{} x {} = {}'.format(numero, 2, numero*2))
print('{} x {} = {}'.format(numero, 3, numero*3))
print('{} x {} = {}'.format(numero, 4, numero*4))
print('{} x {} = {}'.format(numero, 5, numero*5))
print('{} x 6 = {}'.format(numero, numero*6))
print('{} x 7 = {}'.format(numero, numero*7))
print('{} x 8 = {}'.format(numero, numero*8))
print('{} x 9 = {}'.format(numero, numero*9))
print('{} x 10 = {}'.format(numero, numero*10))
print('-' * 15)