tabela = ('PAL', 'CAM', 'COR', 'SAO', 'SAN', 'FLA', 'INT', 'BAH', 'CEA', 'BOT', 'FOR', 'ATP', 'CHAPE', 'GOI', 'FLU', 'CRU', 'CSA', 'GRE', 'AVA', 'VAS')
print('-=' * 50)
print(f'Lista de Times do Brasileirão: {tabela}')
print('-=' * 50)
print(f'Os 5 primeiros são: {tabela[:5]}')
print('-=' * 50)
print(f'Os 4 últimos são: {tabela[-4:]}')
print('-=' * 50)
print(f'Os times na ordem Alfabética são: {sorted(tabela)}')
print('-=' * 50)
print(f'A Chapecoense está na {tabela}º posição.')
