valor = float(input('Digite o valor do produto: R$ '))
outrovalor = float(input("Digite outro valor: R$ "))
descontodooutro = float(input("Digite a porcentagem a dar de desconto: "))
novovalor = outrovalor - (outrovalor * descontodooutro / 100)
novo = valor - (valor * 5 / 100)
novo2 = valor - (valor * 10 / 100)
print("O valor do seu produto com 5% de desconto fica {:.2f}".format(novo))
print("O valor do seu produto com 10% de desconto fica {:.2f}".format(novo2))
print("O valor do produto que voce escolheu o desconto vai ficar R${}".format(novovalor))